"""deneme

Revision ID: 823064cc2ddc
Revises: caa6a2bc780a
Create Date: 2023-11-29 19:24:55.346615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '823064cc2ddc'
down_revision = 'caa6a2bc780a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thread', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thread', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
